[package]
name = "sevenday"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
# card_deck = {path="../../mlibs/card_check"} local library
